from app import db

class Power(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date)
    powerUnit = db.Column(db.String(64))
    power = db.Column(db.Float)

    def __repr__(self):
        return 'Power Stamp: {} {} {} kvt*ch'.format(self.date, self.powerUnit, self.power)

class Fires(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(64))
    title = db.Column(db.String(200))
    year2001 = db.Column(db.Float)
    year2002 = db.Column(db.Float)
    year2003 = db.Column(db.Float)
    year2004 = db.Column(db.Float)
    year2005 = db.Column(db.Float)
    year2006 = db.Column(db.Float)
    year2007 = db.Column(db.Float)
    year2008 = db.Column(db.Float)
    year2009 = db.Column(db.Float)
    year2010 = db.Column(db.Float)
    year2011 = db.Column(db.Float)
    year2012 = db.Column(db.Float)
    year2013 = db.Column(db.Float)
    year2014 = db.Column(db.Float)
    year2015 = db.Column(db.Float)
    year2016 = db.Column(db.Float)
    year2017 = db.Column(db.Float)
    year2018 = db.Column(db.Float)
    year2019 = db.Column(db.Float)
    year2020 = db.Column(db.Float)
    year2021 = db.Column(db.Float)
    year2022 = db.Column(db.Float)
    area = db.Column(db.Float)

    def __repr__(self):
        return 'OOPT: {} {}'.format(self.category, self.title)

class Regions(db.Model):
    region_entry_id = db.Column(db.Integer, primary_key=True)
    oopt_id = db.Column(db.Integer, db.ForeignKey('fires.id'))
    title = db.Column(db.String(100))
    region = db.Column(db.String(100))

    def __repr__(self):
        return 'Fires: {} {} {} '.format(self.region_entry_id, self.oopt_id, self.region)

class Firms(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(64))
    title = db.Column(db.String(200))
    area2001 = db.Column(db.Float)
    firmcount2001 = db.Column(db.Integer)
    area2002 = db.Column(db.Float)
    firmcount2002 = db.Column(db.Integer)
    area2003 = db.Column(db.Float)
    firmcount2003 = db.Column(db.Integer)
    area2004 = db.Column(db.Float)
    firmcount2004 = db.Column(db.Integer)
    area2005 = db.Column(db.Float)
    firmcount2005 = db.Column(db.Integer)
    area2006 = db.Column(db.Float)
    firmcount2006 = db.Column(db.Integer)
    area2007 = db.Column(db.Float)
    firmcount2007 = db.Column(db.Integer)
    area2008 = db.Column(db.Float)
    firmcount2008 = db.Column(db.Integer)
    area2009 = db.Column(db.Float)
    firmcount2009 = db.Column(db.Integer)
    area2010 = db.Column(db.Float)
    firmcount2010 = db.Column(db.Integer)
    area2011 = db.Column(db.Float)
    firmcount2011 = db.Column(db.Integer)
    area2012 = db.Column(db.Float)
    firmcount2012 = db.Column(db.Integer)
    area2013 = db.Column(db.Float)
    firmcount2013 = db.Column(db.Integer)
    area2014 = db.Column(db.Float)
    firmcount2014 = db.Column(db.Integer)
    area2015 = db.Column(db.Float)
    firmcount2015 = db.Column(db.Integer)
    area2016 = db.Column(db.Float)
    firmcount2016 = db.Column(db.Integer)
    area2017 = db.Column(db.Float)
    firmcount2017 = db.Column(db.Integer)
    area2018 = db.Column(db.Float)
    firmcount2018 = db.Column(db.Integer)
    area2019 = db.Column(db.Float)
    firmcount2019 = db.Column(db.Integer)
    area2020 = db.Column(db.Float)
    firmcount2020 = db.Column(db.Integer)
    area2021 = db.Column(db.Float)
    firmcount2021 = db.Column(db.Integer)
    area2022 = db.Column(db.Float)
    firmcount2022 = db.Column(db.Integer)
    area2023 = db.Column(db.Float)
    firmcount2023 = db.Column(db.Integer)
    def __repr__(self):
        return 'OOPT (firms): {} {}'.format(self.category, self.title)