"""firms table

Revision ID: 10744a23bea2
Revises: 56847929703a
Create Date: 2024-04-06 17:27:31.605915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10744a23bea2'
down_revision = '56847929703a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('area2001', sa.Float(), nullable=True),
    sa.Column('firmcount2001', sa.Integer(), nullable=True),
    sa.Column('area2002', sa.Float(), nullable=True),
    sa.Column('firmcount2002', sa.Integer(), nullable=True),
    sa.Column('area2003', sa.Float(), nullable=True),
    sa.Column('firmcount2003', sa.Integer(), nullable=True),
    sa.Column('area2004', sa.Float(), nullable=True),
    sa.Column('firmcount2004', sa.Integer(), nullable=True),
    sa.Column('area2005', sa.Float(), nullable=True),
    sa.Column('firmcount2005', sa.Integer(), nullable=True),
    sa.Column('area2006', sa.Float(), nullable=True),
    sa.Column('firmcount2006', sa.Integer(), nullable=True),
    sa.Column('area2007', sa.Float(), nullable=True),
    sa.Column('firmcount2007', sa.Integer(), nullable=True),
    sa.Column('area2008', sa.Float(), nullable=True),
    sa.Column('firmcount2008', sa.Integer(), nullable=True),
    sa.Column('area2009', sa.Float(), nullable=True),
    sa.Column('firmcount2009', sa.Integer(), nullable=True),
    sa.Column('area2010', sa.Float(), nullable=True),
    sa.Column('firmcount2010', sa.Integer(), nullable=True),
    sa.Column('area2011', sa.Float(), nullable=True),
    sa.Column('firmcount2011', sa.Integer(), nullable=True),
    sa.Column('area2012', sa.Float(), nullable=True),
    sa.Column('firmcount2012', sa.Integer(), nullable=True),
    sa.Column('area2013', sa.Float(), nullable=True),
    sa.Column('firmcount2013', sa.Integer(), nullable=True),
    sa.Column('area2014', sa.Float(), nullable=True),
    sa.Column('firmcount2014', sa.Integer(), nullable=True),
    sa.Column('area2015', sa.Float(), nullable=True),
    sa.Column('firmcount2015', sa.Integer(), nullable=True),
    sa.Column('area2016', sa.Float(), nullable=True),
    sa.Column('firmcount2016', sa.Integer(), nullable=True),
    sa.Column('area2017', sa.Float(), nullable=True),
    sa.Column('firmcount2017', sa.Integer(), nullable=True),
    sa.Column('area2018', sa.Float(), nullable=True),
    sa.Column('firmcount2018', sa.Integer(), nullable=True),
    sa.Column('area2019', sa.Float(), nullable=True),
    sa.Column('firmcount2019', sa.Integer(), nullable=True),
    sa.Column('area2020', sa.Float(), nullable=True),
    sa.Column('firmcount2020', sa.Integer(), nullable=True),
    sa.Column('area2021', sa.Float(), nullable=True),
    sa.Column('firmcount2021', sa.Integer(), nullable=True),
    sa.Column('area2022', sa.Float(), nullable=True),
    sa.Column('firmcount2022', sa.Integer(), nullable=True),
    sa.Column('area2023', sa.Float(), nullable=True),
    sa.Column('firmcount2023', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firms')
    # ### end Alembic commands ###
