"""fires table

Revision ID: 56847929703a
Revises: 823b55d52941
Create Date: 2024-04-02 16:20:39.870515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56847929703a'
down_revision = '823b55d52941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.Float(), nullable=True))

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('fires', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
