"""fires table

Revision ID: a62aff795f5f
Revises: f2b36ff7b7c5
Create Date: 2024-03-04 16:24:38.108526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62aff795f5f'
down_revision = 'f2b36ff7b7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('year2001', sa.Float(), nullable=True),
    sa.Column('year2002', sa.Float(), nullable=True),
    sa.Column('year2003', sa.Float(), nullable=True),
    sa.Column('year2004', sa.Float(), nullable=True),
    sa.Column('year2005', sa.Float(), nullable=True),
    sa.Column('year2006', sa.Float(), nullable=True),
    sa.Column('year2007', sa.Float(), nullable=True),
    sa.Column('year2008', sa.Float(), nullable=True),
    sa.Column('year2009', sa.Float(), nullable=True),
    sa.Column('year2010', sa.Float(), nullable=True),
    sa.Column('year2011', sa.Float(), nullable=True),
    sa.Column('year2012', sa.Float(), nullable=True),
    sa.Column('year2013', sa.Float(), nullable=True),
    sa.Column('year2014', sa.Float(), nullable=True),
    sa.Column('year2015', sa.Float(), nullable=True),
    sa.Column('year2016', sa.Float(), nullable=True),
    sa.Column('year2017', sa.Float(), nullable=True),
    sa.Column('year2018', sa.Float(), nullable=True),
    sa.Column('year2019', sa.Float(), nullable=True),
    sa.Column('year2020', sa.Float(), nullable=True),
    sa.Column('year2021', sa.Float(), nullable=True),
    sa.Column('year2022', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fires')
    # ### end Alembic commands ###
